// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presence.Web.Data;

#nullable disable

namespace Presence.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326184926_UpdateEventModel")]
    partial class UpdateEventModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Presence.Web.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDateTime = new DateTime(2025, 3, 5, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "March Prayer Meeting",
                            StartDateTime = new DateTime(2025, 3, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDateTime = new DateTime(2025, 3, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brother CJ Sermon",
                            StartDateTime = new DateTime(2025, 3, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            EndDateTime = new DateTime(2025, 3, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brother Jan Sermon",
                            StartDateTime = new DateTime(2025, 3, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Band Practice",
                            StartDateTime = new DateTime(2025, 3, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Type = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
